from datetime import datetime
from sqlalchemy import Boolean, DateTime, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from .database import Base

class RawIntelligence(Base):
    __tablename__ = "raw_intelligence"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    title: Mapped[str] = mapped_column(String(300), default="未命名情报")
    source_url: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    source_type: Mapped[str] = mapped_column(String(50), default="人工录入")
    content: Mapped[str] = mapped_column(Text)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    review_status: Mapped[str] = mapped_column(String(20), default="待分析")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class Organization(Base):
    __tablename__ = "organizations"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    standard_name: Mapped[str] = mapped_column(String(300), index=True)
    org_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    region: Mapped[str | None] = mapped_column(String(200), nullable=True)
    industry_tags: Mapped[str | None] = mapped_column(Text, nullable=True)
    resources: Mapped[str | None] = mapped_column(Text, nullable=True)
    needs: Mapped[str | None] = mapped_column(Text, nullable=True)
    relationship_source: Mapped[str | None] = mapped_column(String(200), nullable=True)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    verification_status: Mapped[str] = mapped_column(String(50), default="待核验")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class Person(Base):
    __tablename__ = "people"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(200), index=True)
    public_role: Mapped[str | None] = mapped_column(Text, nullable=True)
    organization_network: Mapped[str | None] = mapped_column(Text, nullable=True)
    ability_tags: Mapped[str | None] = mapped_column(Text, nullable=True)
    value_provided: Mapped[str | None] = mapped_column(Text, nullable=True)
    relationship_source: Mapped[str | None] = mapped_column(String(200), nullable=True)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    verification_status: Mapped[str] = mapped_column(String(50), default="待核验")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class Resource(Base):
    __tablename__ = "resources"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    owner_external_id: Mapped[str] = mapped_column(String(80), index=True)
    owner_organization_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    category: Mapped[str | None] = mapped_column(String(100), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    region: Mapped[str | None] = mapped_column(String(200), nullable=True)
    applicable_to: Mapped[str | None] = mapped_column(Text, nullable=True)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    verification_status: Mapped[str] = mapped_column(String(50), default="待核验")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class HistoricalEvent(Base):
    __tablename__ = "events"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    event_date: Mapped[str | None] = mapped_column(String(50), nullable=True)
    name: Mapped[str] = mapped_column(String(400))
    event_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    related_entity: Mapped[str | None] = mapped_column(String(100), nullable=True)
    related_organization_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fact_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    system_use: Mapped[str | None] = mapped_column(Text, nullable=True)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    verification_status: Mapped[str] = mapped_column(String(50), default="待核验")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class ProjectPool(Base):
    __tablename__ = "projects"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(300), index=True)
    project_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    owner_external_id: Mapped[str | None] = mapped_column(String(80), nullable=True)
    owner_organization_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    focus_tags: Mapped[str | None] = mapped_column(Text, nullable=True)
    typical_needs: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_actions: Mapped[str | None] = mapped_column(Text, nullable=True)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    status: Mapped[str] = mapped_column(String(100), default="待整理")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class Relation(Base):
    __tablename__ = "relations"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    source_external_id: Mapped[str] = mapped_column(String(80), index=True)
    relation_type: Mapped[str] = mapped_column(String(120))
    target_external_id: Mapped[str] = mapped_column(String(80), index=True)
    period: Mapped[str | None] = mapped_column(String(100), nullable=True)
    evidence_source: Mapped[str | None] = mapped_column(Text, nullable=True)
    visibility: Mapped[str] = mapped_column(String(20), default="内部")
    verification_status: Mapped[str] = mapped_column(String(50), default="待核验")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class ActionItem(Base):
    __tablename__ = "actions"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    external_id: Mapped[str] = mapped_column(String(80), unique=True, index=True)
    task: Mapped[str] = mapped_column(String(400))
    target_external_id: Mapped[str | None] = mapped_column(String(80), nullable=True)
    target_organization_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    completion_standard: Mapped[str | None] = mapped_column(Text, nullable=True)
    owner: Mapped[str | None] = mapped_column(String(100), nullable=True)
    priority: Mapped[str | None] = mapped_column(String(20), nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="未开始")
    suggested_deadline: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    source_title: Mapped[str | None] = mapped_column(String(300), nullable=True)
    source_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    captured_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    model_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    auto_generated_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    confirmed_fields: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deactivated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    deactivated_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    subject_match_method: Mapped[str | None] = mapped_column(String(50), nullable=True)
    subject_matched_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    subject_manually_confirmed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

class ImportLog(Base):
    __tablename__ = "import_logs"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    filename: Mapped[str] = mapped_column(String(300))
    imported_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)
    result_json: Mapped[str] = mapped_column(Text)
